# Generated by Django 4.1.7 on 2023-03-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='src',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='href',
        ),
    ]
