# Generated by Django 4.1.7 on 2023-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='feature',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
