# Generated by Django 4.1.7 on 2023-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Лимитировыные товары'),
        ),
    ]
