# Generated by Django 4.1.7 on 2023-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_product_limited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Лимитированные товары'),
        ),
    ]
