# Generated by Django 4.1.7 on 2023-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0009_alter_product_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.SlugField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='app_products.tag', verbose_name='Таги'),
        ),
    ]
