# Generated by Django 4.1.7 on 2023-04-07 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_products', '0010_tag_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsideCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='app_products.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Содержание корзины',
                'verbose_name_plural': 'Содержание корзин',
            },
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=40, verbose_name='Сессия')),
                ('cart', models.ManyToManyField(blank=True, related_name='carts', through='app_basket.InsideCart', to='app_products.product', verbose_name='Содержание корзины')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Чья корзина')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
        migrations.AddField(
            model_name='insidecart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inside', to='app_basket.usercart'),
        ),
    ]
